### ISSUE TITLE
House choice menu bug

### ISSUE THREAD

**Issue by dunajski** [IWiercik/Monopoly-World-Of-Warcraft-edition#3]
![image](https://user-images.githubusercontent.com/46728997/82121332-7f966600-978c-11ea-8689-f8486db91868.png)

I've got problem with buying menu, I can't take less than 3 houses.

**Comment by Swiatlon** [comment]
Sorry, I forget to delete testing function, now will work :P

**Comment by dunajski** [comment]
![image](https://user-images.githubusercontent.com/46728997/89002168-b0525a00-d2fc-11ea-9a0c-6fc07f33197c.png)
:relaxed: 
It should be: KUPUJĘ instead of KUPUJE
