### ISSUE TITLE
Money amount

### ISSUE THREAD

**Issue by dunajski** [IWiercik/Monopoly-World-Of-Warcraft-edition#5]
Few of players have NaN amount of gold. 
I think it should be 0 or values with sign or something.

**Comment by Swiatlon** [comment]
Ok I will repair it Sir !

**Comment by dunajski** [comment]
![image](https://user-images.githubusercontent.com/46728997/89001946-0ecb0880-d2fc-11ea-874d-22525a806b3f.png)
:relieved:
