### ISSUE TITLE
Default buy option

### ISSUE THREAD

**Issue by dunajski** [IWiercik/Monopoly-World-Of-Warcraft-edition#7]
It's feature request issue.
What do you think to set default radio button checked when step on property?

For example, when property belongs to nobody then when you step on it, there will be radio button **Pole** checked and then you can just click **Kupuję**. One click less.

![image](https://user-images.githubusercontent.com/46728997/90474284-3bb55300-e125-11ea-82ad-017e93f21421.png)

**Comment by Swiatlon** [comment]
What about if someone don't want to buy it ?

**Comment by dunajski** [comment]
I think simple cross in right upper corner to close window will be fine. Now it's not obvious what to do when do you want to do nothing. Or maybe simple button **nie rób nic** or something similar next to **Kupuje**.
